// Bundled, hand-curated list of major world commercial airports — used to
// power the departure/destination autocomplete. Deliberately not a live API:
// this app already had one feature (Nearby Places) silently break in
// production because an external API key was never configured, and this
// avoids that whole risk class. Covers every multi-airport city and every
// code already referenced elsewhere in this file (AIRPORT_UTC_OFFSET) or in
// the backend's BORDER_COUNTRY_RULES.
//
// icao is only populated for major hub airports where the code can be
// stated with high confidence — smaller/regional airports are still fully
// searchable by city name and IATA code, just not ICAO.
export const AIRPORTS = [
  // ── Canada ──────────────────────────────────────────────────────────
  { city: "Toronto", country: "Canada", iata: "YYZ", icao: "CYYZ", name: "Toronto Pearson International" },
  { city: "Toronto", country: "Canada", iata: "YTZ", icao: "CYTZ", name: "Billy Bishop Toronto City" },
  { city: "Montreal", country: "Canada", iata: "YUL", icao: "CYUL", name: "Montréal–Trudeau International" },
  { city: "Ottawa", country: "Canada", iata: "YOW", icao: "CYOW", name: "Ottawa Macdonald–Cartier International" },
  { city: "Halifax", country: "Canada", iata: "YHZ", icao: "CYHZ", name: "Halifax Stanfield International" },
  { city: "Quebec City", country: "Canada", iata: "YQB", name: "Québec City Jean Lesage International" },
  { city: "Moncton", country: "Canada", iata: "YQM", name: "Greater Moncton Roméo LeBlanc International" },
  { city: "Fredericton", country: "Canada", iata: "YFC", name: "Fredericton International" },
  { city: "Saint John", country: "Canada", iata: "YSJ", name: "Saint John Airport" },
  { city: "Charlottetown", country: "Canada", iata: "YYG", name: "Charlottetown Airport" },
  { city: "Winnipeg", country: "Canada", iata: "YWG", icao: "CYWG", name: "Winnipeg James Armstrong Richardson International" },
  { city: "Calgary", country: "Canada", iata: "YYC", icao: "CYYC", name: "Calgary International" },
  { city: "Edmonton", country: "Canada", iata: "YEG", icao: "CYEG", name: "Edmonton International" },
  { city: "Vancouver", country: "Canada", iata: "YVR", icao: "CYVR", name: "Vancouver International" },
  { city: "Victoria", country: "Canada", iata: "YYJ", name: "Victoria International" },
  { city: "Saskatoon", country: "Canada", iata: "YXE", name: "Saskatoon John G. Diefenbaker International" },
  { city: "Regina", country: "Canada", iata: "YQR", name: "Regina International" },
  { city: "Abbotsford", country: "Canada", iata: "YXX", name: "Abbotsford International" },
  { city: "London", country: "Canada", iata: "YXU", name: "London International (Ontario)" },
  { city: "Hamilton", country: "Canada", iata: "YHM", name: "John C. Munro Hamilton International" },
  { city: "Thunder Bay", country: "Canada", iata: "YQT", name: "Thunder Bay International" },
  { city: "Yellowknife", country: "Canada", iata: "YZF", name: "Yellowknife Airport" },

  // ── USA — multi-airport cities & major hubs ─────────────────────────
  { city: "New York", country: "USA", iata: "JFK", icao: "KJFK", name: "John F. Kennedy International" },
  { city: "New York", country: "USA", iata: "LGA", icao: "KLGA", name: "LaGuardia" },
  { city: "Newark", country: "USA", iata: "EWR", icao: "KEWR", name: "Newark Liberty International" },
  { city: "Washington", country: "USA", iata: "IAD", icao: "KIAD", name: "Washington Dulles International" },
  { city: "Washington", country: "USA", iata: "DCA", icao: "KDCA", name: "Ronald Reagan Washington National" },
  { city: "Baltimore", country: "USA", iata: "BWI", name: "Baltimore/Washington International" },
  { city: "Boston", country: "USA", iata: "BOS", icao: "KBOS", name: "Logan International" },
  { city: "Philadelphia", country: "USA", iata: "PHL", name: "Philadelphia International" },
  { city: "Chicago", country: "USA", iata: "ORD", icao: "KORD", name: "O'Hare International" },
  { city: "Chicago", country: "USA", iata: "MDW", name: "Midway International" },
  { city: "Detroit", country: "USA", iata: "DTW", name: "Detroit Metropolitan Wayne County" },
  { city: "Minneapolis", country: "USA", iata: "MSP", name: "Minneapolis–Saint Paul International" },
  { city: "Atlanta", country: "USA", iata: "ATL", icao: "KATL", name: "Hartsfield–Jackson Atlanta International" },
  { city: "Miami", country: "USA", iata: "MIA", icao: "KMIA", name: "Miami International" },
  { city: "Fort Lauderdale", country: "USA", iata: "FLL", name: "Fort Lauderdale–Hollywood International" },
  { city: "Orlando", country: "USA", iata: "MCO", name: "Orlando International" },
  { city: "Tampa", country: "USA", iata: "TPA", name: "Tampa International" },
  { city: "Fort Myers", country: "USA", iata: "RSW", name: "Southwest Florida International" },
  { city: "Dallas", country: "USA", iata: "DFW", icao: "KDFW", name: "Dallas/Fort Worth International" },
  { city: "Dallas", country: "USA", iata: "DAL", name: "Dallas Love Field" },
  { city: "Houston", country: "USA", iata: "IAH", icao: "KIAH", name: "George Bush Intercontinental" },
  { city: "Houston", country: "USA", iata: "HOU", name: "William P. Hobby" },
  { city: "Austin", country: "USA", iata: "AUS", name: "Austin-Bergstrom International" },
  { city: "San Antonio", country: "USA", iata: "SAT", name: "San Antonio International" },
  { city: "Denver", country: "USA", iata: "DEN", icao: "KDEN", name: "Denver International" },
  { city: "Phoenix", country: "USA", iata: "PHX", icao: "KPHX", name: "Phoenix Sky Harbor International" },
  { city: "Las Vegas", country: "USA", iata: "LAS", icao: "KLAS", name: "Harry Reid International" },
  { city: "Los Angeles", country: "USA", iata: "LAX", icao: "KLAX", name: "Los Angeles International" },
  { city: "San Diego", country: "USA", iata: "SAN", name: "San Diego International" },
  { city: "Santa Ana", country: "USA", iata: "SNA", name: "John Wayne Airport (Orange County)" },
  { city: "Ontario", country: "USA", iata: "ONT", name: "Ontario International" },
  { city: "San Francisco", country: "USA", iata: "SFO", icao: "KSFO", name: "San Francisco International" },
  { city: "Oakland", country: "USA", iata: "OAK", name: "Oakland International" },
  { city: "San Jose", country: "USA", iata: "SJC", name: "San José Mineta International" },
  { city: "Sacramento", country: "USA", iata: "SMF", name: "Sacramento International" },
  { city: "Seattle", country: "USA", iata: "SEA", icao: "KSEA", name: "Seattle–Tacoma International" },
  { city: "Portland", country: "USA", iata: "PDX", name: "Portland International" },
  { city: "Charlotte", country: "USA", iata: "CLT", name: "Charlotte Douglas International" },
  { city: "Raleigh", country: "USA", iata: "RDU", name: "Raleigh-Durham International" },
  { city: "Salt Lake City", country: "USA", iata: "SLC", name: "Salt Lake City International" },
  { city: "Honolulu", country: "USA", iata: "HNL", name: "Daniel K. Inouye International" },
  { city: "Nashville", country: "USA", iata: "BNA", name: "Nashville International" },
  { city: "Milwaukee", country: "USA", iata: "MKE", name: "Milwaukee Mitchell International" },
  { city: "New Orleans", country: "USA", iata: "MSY", name: "Louis Armstrong New Orleans International" },
  { city: "Pittsburgh", country: "USA", iata: "PIT", name: "Pittsburgh International" },
  { city: "Columbus", country: "USA", iata: "CMH", name: "John Glenn Columbus International" },
  { city: "Albuquerque", country: "USA", iata: "ABQ", name: "Albuquerque International Sunport" },
  { city: "Buffalo", country: "USA", iata: "BUF", name: "Buffalo Niagara International" },
  { city: "Providence", country: "USA", iata: "PVD", name: "T. F. Green International" },
  { city: "Jacksonville", country: "USA", iata: "JAX", name: "Jacksonville International" },
  { city: "Anchorage", country: "USA", iata: "ANC", name: "Ted Stevens Anchorage International" },
  { city: "Cleveland", country: "USA", iata: "CLE", name: "Cleveland Hopkins International" },
  { city: "Indianapolis", country: "USA", iata: "IND", name: "Indianapolis International" },
  { city: "Cincinnati", country: "USA", iata: "CVG", name: "Cincinnati/Northern Kentucky International" },
  { city: "Omaha", country: "USA", iata: "OMA", name: "Eppley Airfield" },
  { city: "Kansas City", country: "USA", iata: "KCI", name: "Kansas City International" },
  { city: "Grand Rapids", country: "USA", iata: "GRR", name: "Gerald R. Ford International" },
  { city: "Hartford", country: "USA", iata: "BDL", name: "Bradley International" },
  { city: "Norfolk", country: "USA", iata: "ORF", name: "Norfolk International" },
  { city: "Richmond", country: "USA", iata: "RIC", name: "Richmond International" },
  { city: "Spokane", country: "USA", iata: "GEG", name: "Spokane International" },
  { city: "Memphis", country: "USA", iata: "MEM", name: "Memphis International" },
  { city: "Birmingham", country: "USA", iata: "BHM", name: "Birmingham–Shuttlesworth International" },
  { city: "Tucson", country: "USA", iata: "TUS", name: "Tucson International" },
  { city: "El Paso", country: "USA", iata: "ELP", name: "El Paso International" },
  { city: "St. Louis", country: "USA", iata: "STL", name: "St. Louis Lambert International" },

  // ── Caribbean / Mexico / Central America ────────────────────────────
  { city: "Nassau", country: "Bahamas", iata: "NAS", name: "Lynden Pindling International" },
  { city: "Montego Bay", country: "Jamaica", iata: "MBJ", name: "Sangster International" },
  { city: "Kingston", country: "Jamaica", iata: "KIN", name: "Norman Manley International" },
  { city: "Punta Cana", country: "Dominican Republic", iata: "PUJ", name: "Punta Cana International" },
  { city: "San Juan", country: "Puerto Rico", iata: "SJU", name: "Luis Muñoz Marín International" },
  { city: "Aruba", country: "Aruba", iata: "AUA", name: "Queen Beatrix International" },
  { city: "Bridgetown", country: "Barbados", iata: "BGI", name: "Grantley Adams International" },
  { city: "Havana", country: "Cuba", iata: "HAV", name: "José Martí International" },
  { city: "Cancún", country: "Mexico", iata: "CUN", name: "Cancún International" },
  { city: "Mexico City", country: "Mexico", iata: "MEX", icao: "MMMX", name: "Mexico City International" },
  { city: "Panama City", country: "Panama", iata: "PTY", name: "Tocumen International" },

  // ── South America ───────────────────────────────────────────────────
  { city: "São Paulo", country: "Brazil", iata: "GRU", icao: "SBGR", name: "São Paulo/Guarulhos International" },
  { city: "São Paulo", country: "Brazil", iata: "CGH", name: "Congonhas Airport" },
  { city: "Rio de Janeiro", country: "Brazil", iata: "GIG", name: "Rio de Janeiro/Galeão International" },
  { city: "Rio de Janeiro", country: "Brazil", iata: "SDU", name: "Santos Dumont Airport" },
  { city: "Buenos Aires", country: "Argentina", iata: "EZE", icao: "SAEZ", name: "Ministro Pistarini International (Ezeiza)" },
  { city: "Buenos Aires", country: "Argentina", iata: "AEP", name: "Jorge Newbery Airfield" },
  { city: "Bogotá", country: "Colombia", iata: "BOG", icao: "SKBO", name: "El Dorado International" },
  { city: "Lima", country: "Peru", iata: "LIM", name: "Jorge Chávez International" },
  { city: "Santiago", country: "Chile", iata: "SCL", name: "Arturo Merino Benítez International" },
  { city: "Quito", country: "Ecuador", iata: "UIO", name: "Mariscal Sucre International" },

  // ── UK / Ireland ─────────────────────────────────────────────────────
  { city: "London", country: "UK", iata: "LHR", icao: "EGLL", name: "Heathrow" },
  { city: "London", country: "UK", iata: "LGW", icao: "EGKK", name: "Gatwick" },
  { city: "London", country: "UK", iata: "LCY", name: "London City" },
  { city: "London", country: "UK", iata: "STN", icao: "EGSS", name: "Stansted" },
  { city: "London", country: "UK", iata: "LTN", name: "Luton" },
  { city: "Manchester", country: "UK", iata: "MAN", icao: "EGCC", name: "Manchester Airport" },
  { city: "Edinburgh", country: "UK", iata: "EDI", name: "Edinburgh Airport" },
  { city: "Glasgow", country: "UK", iata: "GLA", name: "Glasgow Airport" },
  { city: "Birmingham", country: "UK", iata: "BHX", name: "Birmingham Airport" },
  { city: "Bristol", country: "UK", iata: "BRS", name: "Bristol Airport" },
  { city: "Newcastle", country: "UK", iata: "NCL", name: "Newcastle Airport" },
  { city: "Leeds", country: "UK", iata: "LBA", name: "Leeds Bradford Airport" },
  { city: "Aberdeen", country: "UK", iata: "ABZ", name: "Aberdeen Airport" },
  { city: "Belfast", country: "UK", iata: "BFS", name: "Belfast International" },
  { city: "Belfast", country: "UK", iata: "BHD", name: "George Best Belfast City" },
  { city: "Southampton", country: "UK", iata: "SOU", name: "Southampton Airport" },
  { city: "Exeter", country: "UK", iata: "EXT", name: "Exeter Airport" },
  { city: "Cardiff", country: "UK", iata: "CWL", name: "Cardiff Airport" },
  { city: "Dublin", country: "Ireland", iata: "DUB", icao: "EIDW", name: "Dublin Airport" },
  { city: "Cork", country: "Ireland", iata: "ORK", name: "Cork Airport" },
  { city: "Shannon", country: "Ireland", iata: "SNN", name: "Shannon Airport" },

  // ── Europe ───────────────────────────────────────────────────────────
  { city: "Paris", country: "France", iata: "CDG", icao: "LFPG", name: "Charles de Gaulle" },
  { city: "Paris", country: "France", iata: "ORY", icao: "LFPO", name: "Orly" },
  { city: "Nice", country: "France", iata: "NCE", name: "Nice Côte d'Azur" },
  { city: "Lyon", country: "France", iata: "LYS", name: "Lyon–Saint Exupéry" },
  { city: "Marseille", country: "France", iata: "MRS", name: "Marseille Provence" },
  { city: "Toulouse", country: "France", iata: "TLS", name: "Toulouse–Blagnac" },
  { city: "Nantes", country: "France", iata: "NTE", name: "Nantes Atlantique" },
  { city: "Bordeaux", country: "France", iata: "BOD", name: "Bordeaux–Mérignac" },
  { city: "Strasbourg", country: "France", iata: "SXB", name: "Strasbourg Airport" },
  { city: "Montpellier", country: "France", iata: "MPL", name: "Montpellier–Méditerranée" },
  { city: "Lille", country: "France", iata: "LIL", name: "Lille Airport" },
  { city: "Frankfurt", country: "Germany", iata: "FRA", icao: "EDDF", name: "Frankfurt Airport" },
  { city: "Munich", country: "Germany", iata: "MUC", icao: "EDDM", name: "Munich Airport" },
  { city: "Berlin", country: "Germany", iata: "BER", icao: "EDDB", name: "Berlin Brandenburg" },
  { city: "Hamburg", country: "Germany", iata: "HAM", name: "Hamburg Airport" },
  { city: "Düsseldorf", country: "Germany", iata: "DUS", name: "Düsseldorf Airport" },
  { city: "Cologne", country: "Germany", iata: "CGN", name: "Cologne Bonn Airport" },
  { city: "Stuttgart", country: "Germany", iata: "STR", name: "Stuttgart Airport" },
  { city: "Nuremberg", country: "Germany", iata: "NUE", name: "Nuremberg Airport" },
  { city: "Hannover", country: "Germany", iata: "HAJ", name: "Hannover Airport" },
  { city: "Dortmund", country: "Germany", iata: "DTM", name: "Dortmund Airport" },
  { city: "Leipzig", country: "Germany", iata: "LEJ", name: "Leipzig/Halle Airport" },
  { city: "Amsterdam", country: "Netherlands", iata: "AMS", icao: "EHAM", name: "Amsterdam Airport Schiphol" },
  { city: "Eindhoven", country: "Netherlands", iata: "EIN", name: "Eindhoven Airport" },
  { city: "Brussels", country: "Belgium", iata: "BRU", icao: "EBBR", name: "Brussels Airport" },
  { city: "Charleroi", country: "Belgium", iata: "CRL", name: "Brussels South Charleroi" },
  { city: "Luxembourg", country: "Luxembourg", iata: "LUX", name: "Luxembourg Airport" },
  { city: "Madrid", country: "Spain", iata: "MAD", icao: "LEMD", name: "Adolfo Suárez Madrid–Barajas" },
  { city: "Barcelona", country: "Spain", iata: "BCN", icao: "LEBL", name: "Josep Tarradellas Barcelona-El Prat" },
  { city: "Palma de Mallorca", country: "Spain", iata: "PMI", name: "Palma de Mallorca Airport" },
  { city: "Málaga", country: "Spain", iata: "AGP", name: "Málaga Airport" },
  { city: "Alicante", country: "Spain", iata: "ALC", name: "Alicante Airport" },
  { city: "Valencia", country: "Spain", iata: "VLC", name: "Valencia Airport" },
  { city: "Seville", country: "Spain", iata: "SVQ", name: "Seville Airport" },
  { city: "Lisbon", country: "Portugal", iata: "LIS", icao: "LPPT", name: "Humberto Delgado Airport" },
  { city: "Porto", country: "Portugal", iata: "OPO", name: "Francisco Sá Carneiro Airport" },
  { city: "Faro", country: "Portugal", iata: "FAO", name: "Faro Airport" },
  { city: "Rome", country: "Italy", iata: "FCO", icao: "LIRF", name: "Leonardo da Vinci–Fiumicino" },
  { city: "Rome", country: "Italy", iata: "CIA", name: "Ciampino Airport" },
  { city: "Milan", country: "Italy", iata: "MXP", icao: "LIMC", name: "Milan Malpensa" },
  { city: "Milan", country: "Italy", iata: "LIN", name: "Milan Linate" },
  { city: "Milan", country: "Italy", iata: "BGY", name: "Milan Bergamo (Orio al Serio)" },
  { city: "Naples", country: "Italy", iata: "NAP", name: "Naples International" },
  { city: "Venice", country: "Italy", iata: "VCE", name: "Venice Marco Polo" },
  { city: "Bologna", country: "Italy", iata: "BLQ", name: "Bologna Guglielmo Marconi" },
  { city: "Catania", country: "Italy", iata: "CTA", name: "Catania–Fontanarossa" },
  { city: "Palermo", country: "Italy", iata: "PMO", name: "Falcone–Borsellino Airport" },
  { city: "Zurich", country: "Switzerland", iata: "ZRH", icao: "LSZH", name: "Zurich Airport" },
  { city: "Geneva", country: "Switzerland", iata: "GVA", name: "Geneva Airport" },
  { city: "Basel", country: "Switzerland", iata: "BSL", name: "EuroAirport Basel-Mulhouse-Freiburg" },
  { city: "Vienna", country: "Austria", iata: "VIE", icao: "LOWW", name: "Vienna International" },
  { city: "Salzburg", country: "Austria", iata: "SZG", name: "Salzburg Airport" },
  { city: "Stockholm", country: "Sweden", iata: "ARN", icao: "ESSA", name: "Stockholm Arlanda" },
  { city: "Gothenburg", country: "Sweden", iata: "GOT", name: "Gothenburg Landvetter" },
  { city: "Malmö", country: "Sweden", iata: "MMX", name: "Malmö Airport" },
  { city: "Copenhagen", country: "Denmark", iata: "CPH", icao: "EKCH", name: "Copenhagen Airport" },
  { city: "Aalborg", country: "Denmark", iata: "AAL", name: "Aalborg Airport" },
  { city: "Billund", country: "Denmark", iata: "BLL", name: "Billund Airport" },
  { city: "Oslo", country: "Norway", iata: "OSL", icao: "ENGM", name: "Oslo Gardermoen" },
  { city: "Bergen", country: "Norway", iata: "BGO", name: "Bergen Airport" },
  { city: "Trondheim", country: "Norway", iata: "TRD", name: "Trondheim Airport" },
  { city: "Helsinki", country: "Finland", iata: "HEL", icao: "EFHK", name: "Helsinki Airport" },
  { city: "Tampere", country: "Finland", iata: "TMP", name: "Tampere-Pirkkala Airport" },
  { city: "Warsaw", country: "Poland", iata: "WAW", icao: "EPWA", name: "Warsaw Chopin Airport" },
  { city: "Kraków", country: "Poland", iata: "KRK", name: "Kraków John Paul II International" },
  { city: "Prague", country: "Czech Republic", iata: "PRG", icao: "LKPR", name: "Václav Havel Airport Prague" },
  { city: "Budapest", country: "Hungary", iata: "BUD", icao: "LHBP", name: "Budapest Ferenc Liszt International" },
  { city: "Bucharest", country: "Romania", iata: "OTP", name: "Henri Coandă International" },
  { city: "Sofia", country: "Bulgaria", iata: "SOF", name: "Sofia Airport" },
  { city: "Ljubljana", country: "Slovenia", iata: "LJU", name: "Ljubljana Jože Pučnik Airport" },
  { city: "Zagreb", country: "Croatia", iata: "ZAG", name: "Zagreb Airport" },
  { city: "Riga", country: "Latvia", iata: "RIX", name: "Riga International" },
  { city: "Tallinn", country: "Estonia", iata: "TLL", name: "Tallinn Airport" },
  { city: "Vilnius", country: "Lithuania", iata: "VNO", name: "Vilnius Airport" },
  { city: "Athens", country: "Greece", iata: "ATH", icao: "LGAV", name: "Athens International" },
  { city: "Thessaloniki", country: "Greece", iata: "SKG", name: "Thessaloniki Airport" },
  { city: "Heraklion", country: "Greece", iata: "HER", name: "Heraklion International" },
  { city: "Rhodes", country: "Greece", iata: "RHO", name: "Rhodes International" },
  { city: "Istanbul", country: "Turkey", iata: "IST", icao: "LTFM", name: "Istanbul Airport" },
  { city: "Malta", country: "Malta", iata: "MLA", name: "Malta International" },
  { city: "Moscow", country: "Russia", iata: "SVO", name: "Sheremetyevo International" },
  { city: "Moscow", country: "Russia", iata: "DME", name: "Domodedovo International" },
  { city: "Moscow", country: "Russia", iata: "VKO", name: "Vnukovo International" },

  // ── Middle East / Africa ─────────────────────────────────────────────
  { city: "Dubai", country: "UAE", iata: "DXB", icao: "OMDB", name: "Dubai International" },
  { city: "Dubai", country: "UAE", iata: "DWC", name: "Al Maktoum International" },
  { city: "Abu Dhabi", country: "UAE", iata: "AUH", icao: "OMAA", name: "Zayed International" },
  { city: "Sharjah", country: "UAE", iata: "SHJ", name: "Sharjah International" },
  { city: "Al Ain", country: "UAE", iata: "AAN", name: "Al Ain International" },
  { city: "Ras Al Khaimah", country: "UAE", iata: "RKT", name: "Ras Al Khaimah International" },
  { city: "Fujairah", country: "UAE", iata: "FJR", name: "Fujairah International" },
  { city: "Doha", country: "Qatar", iata: "DOH", icao: "OTHH", name: "Hamad International" },
  { city: "Muscat", country: "Oman", iata: "MCT", name: "Muscat International" },
  { city: "Salalah", country: "Oman", iata: "SLL", name: "Salalah Airport" },
  { city: "Kuwait City", country: "Kuwait", iata: "KWI", name: "Kuwait International" },
  { city: "Manama", country: "Bahrain", iata: "BAH", name: "Bahrain International" },
  { city: "Riyadh", country: "Saudi Arabia", iata: "RUH", name: "King Khalid International" },
  { city: "Jeddah", country: "Saudi Arabia", iata: "JED", name: "King Abdulaziz International" },
  { city: "Dammam", country: "Saudi Arabia", iata: "DMM", name: "King Fahd International" },
  { city: "Medina", country: "Saudi Arabia", iata: "MED", name: "Prince Mohammad Bin Abdulaziz Airport" },
  { city: "Tabuk", country: "Saudi Arabia", iata: "TUU", name: "Tabuk Regional Airport" },
  { city: "Abha", country: "Saudi Arabia", iata: "AHB", name: "Abha International" },
  { city: "Gizan", country: "Saudi Arabia", iata: "GIZ", name: "Jizan Regional Airport" },
  { city: "Tel Aviv", country: "Israel", iata: "TLV", icao: "LLBG", name: "Ben Gurion Airport" },
  { city: "Cairo", country: "Egypt", iata: "CAI", icao: "HECA", name: "Cairo International" },
  { city: "Casablanca", country: "Morocco", iata: "CMN", name: "Mohammed V International" },
  { city: "Johannesburg", country: "South Africa", iata: "JNB", icao: "FAOR", name: "OR Tambo International" },
  { city: "Nairobi", country: "Kenya", iata: "NBO", name: "Jomo Kenyatta International" },

  // ── Asia / Pacific ────────────────────────────────────────────────────
  { city: "Tokyo", country: "Japan", iata: "NRT", icao: "RJAA", name: "Narita International" },
  { city: "Tokyo", country: "Japan", iata: "HND", icao: "RJTT", name: "Haneda Airport" },
  { city: "Osaka", country: "Japan", iata: "KIX", icao: "RJBB", name: "Kansai International" },
  { city: "Nagoya", country: "Japan", iata: "NGO", name: "Chubu Centrair International" },
  { city: "Sapporo", country: "Japan", iata: "CTS", name: "New Chitose Airport" },
  { city: "Fukuoka", country: "Japan", iata: "FUK", name: "Fukuoka Airport" },
  { city: "Okinawa", country: "Japan", iata: "OKA", name: "Naha Airport" },
  { city: "Oita", country: "Japan", iata: "OIT", name: "Oita Airport" },
  { city: "Miyazaki", country: "Japan", iata: "KMI", name: "Miyazaki Airport" },
  { city: "Kumamoto", country: "Japan", iata: "KMJ", name: "Kumamoto Airport" },
  { city: "Sendai", country: "Japan", iata: "SDJ", name: "Sendai Airport" },
  { city: "Seoul", country: "South Korea", iata: "ICN", icao: "RKSI", name: "Incheon International" },
  { city: "Seoul", country: "South Korea", iata: "GMP", name: "Gimpo International" },
  { city: "Beijing", country: "China", iata: "PEK", icao: "ZBAA", name: "Beijing Capital International" },
  { city: "Beijing", country: "China", iata: "PKX", name: "Beijing Daxing International" },
  { city: "Shanghai", country: "China", iata: "PVG", icao: "ZSPD", name: "Shanghai Pudong International" },
  { city: "Shanghai", country: "China", iata: "SHA", name: "Shanghai Hongqiao International" },
  { city: "Hong Kong", country: "Hong Kong", iata: "HKG", icao: "VHHH", name: "Hong Kong International" },
  { city: "Singapore", country: "Singapore", iata: "SIN", icao: "WSSS", name: "Singapore Changi" },
  { city: "Bangkok", country: "Thailand", iata: "BKK", icao: "VTBS", name: "Suvarnabhumi Airport" },
  { city: "Bangkok", country: "Thailand", iata: "DMK", name: "Don Mueang International" },
  { city: "Kuala Lumpur", country: "Malaysia", iata: "KUL", icao: "WMKK", name: "Kuala Lumpur International" },
  { city: "Delhi", country: "India", iata: "DEL", icao: "VIDP", name: "Indira Gandhi International" },
  { city: "Mumbai", country: "India", iata: "BOM", icao: "VABB", name: "Chhatrapati Shivaji Maharaj International" },
  { city: "Sydney", country: "Australia", iata: "SYD", icao: "YSSY", name: "Sydney Kingsford Smith" },
  { city: "Melbourne", country: "Australia", iata: "MEL", icao: "YMML", name: "Melbourne Airport" },
  { city: "Brisbane", country: "Australia", iata: "BNE", name: "Brisbane Airport" },
  { city: "Perth", country: "Australia", iata: "PER", name: "Perth Airport" },
  { city: "Adelaide", country: "Australia", iata: "ADL", name: "Adelaide Airport" },
  { city: "Canberra", country: "Australia", iata: "CBR", name: "Canberra Airport" },
  { city: "Gold Coast", country: "Australia", iata: "OOL", name: "Gold Coast Airport" },
  { city: "Cairns", country: "Australia", iata: "CNS", name: "Cairns Airport" },
  { city: "Darwin", country: "Australia", iata: "DRW", name: "Darwin Airport" },
  { city: "Hobart", country: "Australia", iata: "HBA", name: "Hobart Airport" },
  { city: "Townsville", country: "Australia", iata: "TSV", name: "Townsville Airport" },
  { city: "Mackay", country: "Australia", iata: "MKY", name: "Mackay Airport" },
  { city: "Rockhampton", country: "Australia", iata: "ROK", name: "Rockhampton Airport" },
  { city: "Launceston", country: "Australia", iata: "LST", name: "Launceston Airport" },
  { city: "Auckland", country: "New Zealand", iata: "AKL", icao: "NZAA", name: "Auckland Airport" },
];

// Scores and ranks matches: exact IATA/ICAO code first, then IATA prefix,
// then city name starting with the query, then any city/name substring.
// Pure client-side scan — no debounce needed, this is not a network call.
export function searchAirports(query, limit = 6) {
  const q = (query || "").trim().toLowerCase();
  if (q.length < 2) return [];
  const scored = [];
  for (const a of AIRPORTS) {
    const iata = a.iata.toLowerCase();
    const icao = a.icao?.toLowerCase();
    const city = a.city.toLowerCase();
    const name = a.name.toLowerCase();
    let score = 0;
    if (iata === q || icao === q) score = 100;
    else if (iata.startsWith(q) || icao?.startsWith(q)) score = 80;
    else if (city.startsWith(q)) score = 60;
    else if (city.includes(q)) score = 40;
    else if (name.includes(q)) score = 20;
    if (score > 0) scored.push({ airport: a, score });
  }
  scored.sort((x, y) => y.score - x.score || x.airport.city.localeCompare(y.airport.city));
  return scored.slice(0, limit).map(x => x.airport);
}
